### ISSUE TITLE
Crash while compile with Mono on Linux

### ISSUE THREAD

**Issue by Arakis** [mosa/MOSA-Project#150]
When i run ./Compile.sh, i get this error (round about 100 of them):
```
SSE.cs(22,25): error CS0584: Internal compiler error: Object reference not set to an instance of an object
```
I'm using the latest mono compiler (3.12). It seems, it's bug in the mono compiler itself, but do you know a mono version (or MOSA github revision), where you was able to compile the kernel with mono? I'm using Linux only.

**Comment by charsleysa** [comment]
@arakis I don't know which mono versions work as I work on Windows, but I know there are sometimes concurrency problems with the compiler so running the compilation procedure multiple times may fix your issue. 

You could try mono 3.11

If you are aware of a bug with mono or mosa please submit as much information about the bug as you know. 

There are some known bugs that are currently fixed in unstable development branches in my repo.

**Comment by Arakis** [comment]
I downgraded my mono package to 3.4 and 3.10 (my linux distro skipped 3.11), i still get the same error.
```
			Target CoreCompile:
				Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /delaysign- /debug+ /optimize- /out:obj/Debug/Mosa.Kernel.x86.dll ConsoleManager.cs ConsoleSession.cs SSE.cs DebugClient.cs Serial.cs Debug.cs KernelMemory.cs CMOS.cs Colors.cs CpuInfo.cs GDT.cs IdleTask.cs IDT.cs Kernel.cs Keyboard.cs Memory.cs Multiboot.cs PageFaultHandler.cs PageFrameAllocator.cs PageTable.cs Panic.cs PIC.cs ProcessManager.cs Screen.cs Smbios/BiosInformationStructure.cs Smbios/CpuStructure.cs Smbios/SmbiosManager.cs Smbios/SmbiosStructure.cs TaskManager.cs VirtualPageAllocator.cs /target:library /warnaserror+ /unsafe+ /define:"DEBUG;TRACE" /nowarn:1685;0219;0414 /nostdlib /reference:/usr/lib/mono/4.0/System.Core.dll /reference:/home/sebastian/tmp/MOSA-Project/bin//mscorlib.dll /reference:/home/sebastian/tmp/MOSA-Project/bin//Mosa.Internal.dll /reference:/home/sebastian/tmp/MOSA-Project/bin//Mosa.Platform.Internal.x86.dll /warn:4
SSE.cs(22,25): error CS0584: Internal compiler error: Object reference not set to an instance of an object
				/home/sebastian/tmp/MOSA-Project/bin//mscorlib.dll (Location of the symbol related to previous error)
				/usr/lib/mono/4.0/System.Core.dll (Location of the symbol related to previous error)
SSE.cs(25,25): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(137,18): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(177,11): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(177,11): error CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
DebugClient.cs(212,69): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(247,24): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(265,12): error CS0584: Internal compiler error: Object reference not set to an instance of an object
... and so on ....
```
Did it ever worked on Linux? If yes, the name/version of the used linux distro would be nice (i hate windows).

**Comment by charsleysa** [comment]
Yes, we have tested it before on linux but that was back at version 1.3 I think.

I think there may be a configuration issue with building with Mono.

`/reference:/usr/lib/mono/4.0/System.Core.dll` shouldn't be in the configuration since the solution that is being built utilizes it's own implementation as described by `/reference:/home/sebastian/tmp/MOSA-Project/bin//mscorlib.dll`

This sounds like Mono not picking up the configuration correctly.

A possible solution is this:
for every project that has errors like the ones you posted, go into their directory, open up the `.csproj` file and paste the following line into all the PropertyGroups that have a condition.
`<NoStdLib>true</NoStdLib>`

**Comment by Arakis** [comment]
`<NoStdLib>...` was already in the proj-file, and mcs is called correctly with /nostdlib, but i added it now to ther other PropertyGroups, too, with no success. I even tried to run mcs via command line directly:
```
sebastian@eros Source/Mosa.Kernel.x86 - [master●] $ /usr/lib/mono/4.5/mcs.exe /noconfig /debug:full /delaysign- /debug+ /optimize- /out:obj/Debug/Mosa.Kernel.x86.dll /target:library /warnaserror+ /unsafe+ /define:"DEBUG;TRACE" /nowarn:1685,0219,0414 /nostdlib /reference:/home/sebastian/tmp/MOSA-Project/bin//mscorlib.dll /reference:/home/sebastian/tmp/MOSA-Project/bin//Mosa.Internal.dll /reference:/home/sebastian/tmp/MOSA-Project/bin/Mosa.Platform.Internal.x86.dll /warn:4 ConsoleManager.cs ConsoleSession.cs SSE.cs DebugClient.cs Serial.cs Debug.cs KernelMemory.cs CMOS.cs Colors.cs CpuInfo.cs GDT.cs IdleTask.cs IDT.cs Kernel.cs Keyboard.cs Memory.cs Multiboot.cs PageFaultHandler.cs PageFrameAllocator.cs PageTable.cs Panic.cs PIC.cs ProcessManager.cs Screen.cs Smbios/BiosInformationStructure.cs Smbios/CpuStructure.cs Smbios/SmbiosManager.cs Smbios/SmbiosStructure.cs TaskManager.cs VirtualPageAllocator.cs
SSE.cs(22,25): error CS0584: Internal compiler error: Object reference not set to an instance of an object
SSE.cs(25,25): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(137,18): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(177,11): error CS0584: Internal compiler error: Object reference not set to an instance of an object
DebugClient.cs(177,11): error CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
DebugClient.cs(212,69): error CS0584: Internal compiler error: Object reference not set to an instance of an object
...
```
Maybe it would be an idea to debug mcs itself via `/bin/mono --debug`, but i do not know how to directly connect to the monodevelop debugger. Or i get the mono sources, build & debug mcs (with the specified arguments above).

**Comment by charsleysa** [comment]
Can you please check that `/home/sebastian/tmp/MOSA-Project/bin/` directory contains all the referenced DLLs?

**Comment by Arakis** [comment]
I cleared the bin dir and tried only to rebuild Mosa.Kernel.x86. This are dependencies are generated:
```
sebastian@eros MOSA-Project/bin - [master●] $ l *.dll
-rwxr-xr-x 1 sebastian users 4,0K 20. Jan 21:18 Mosa.Internal.dll
-rwxr-xr-x 1 sebastian users  23K 20. Jan 23:33 Mosa.Platform.Internal.x86.dll
-rwxr-xr-x 1 sebastian users  74K 20. Jan 21:18 mscorlib.dll
```
I tried also to compile/recompile Mosa.Platform.Internal.x86.dll via `mcs`directly (without `/reference:/usr/lib/mono/4.0/System.Core.dll`), `Mosa.Kernel.x86` is still not buildable. Just for information: `Mosa.Platform.Internal.x86` builds fine!

I tried to remove the `DllImportAttribute` on a Native Method, just for testing), than there's one build error lesser. My idea was, maybe mono tries to get the Type `DllImportAttribute` from the default mscorlib.dll instead of the MOSA mscorlib.dll. But this should not the case, because we do not reference to that. But maybe it's hard coded in the compiler ;) I don't know. Maybe i should open a issue on the mono page.

**Comment by charsleysa** [comment]
I think what is happening is that the Mono compiler is trying to resolve the `DllImportAttribute` during compile time, which it really should not be doing.

If this is the case and is the intended functionality of the Mono compiler then we may need to look into using other attributes to describe the methods.

**Comment by charsleysa** [comment]
I will be swapping the native methods over to the Intrinsic replacement system which gets around this issue while still maintaining the full functionality.

This will be done sometime tonight in my Metadata branch which also contains a whole bunch of other fixes and features, then I'll merge it into the main repo.

**Comment by Arakis** [comment]
Just for info: I thought, maybe the compiler takes the wrong reference because of the same assembly name, so i renamed mscorlib.dll to mskorlib.dll - same result. I will now look, how to debug `msc` :-)

By the way, i have a virtual machine here with windows 7 (last used several months ago) and install there now VS2013 - hm...it feels like 10 hours in comparison 10 seconds on Linux :-) (installation time).

**Comment by Arakis** [comment]
The debugging of `mcs` was successfull and i found out why it crashes.

Please add this class to korlib!
```
    [AttributeUsage(AttributeTargets.Method, Inherited = false)]
    [System.Runtime.InteropServices.ComVisible(true)]
    public sealed class PreserveSigAttribute : Attribute
    {
        public PreserveSigAttribute()
        {
        }
    }
```
After that, all will compile. Only some warnings as errors occurs, after disabling this, all is fine.

By the way: Maybe you should make a exception for the Warning "unused variable assigned but never used" or such "invalid" code should not commited. In my opinion, commited source should always buildable without errors.

**Comment by charsleysa** [comment]
@Arakis Awesome work, are you able to create a Pull Request?

That way I can merge the fix straight away, otherwise I won't have time until tonight to do it myself.

**Comment by Arakis** [comment]
No problem, but not yet, i'm watching now tv with my girlfriend.

In generell, i want to have an detailed look at MOSA and Cosmos. I've very interested to help where i can, but now the most hard decision is to decide, in wich project i should help. I think MOSA, because it's buildable on Linux (yay!) and it seems more clean. On the other hand, i see, here's to do *a lot* of work.

I'm interested in creating better framebuffer support for terminal fond output, virtual terminals, implementing a fully functional VT220 emulation. But for that, i need to discuss with you, and become more background information. For example, why don't you use UIntPtr instead of uint32 when working with memory pointers? It's better for future x64 support. Do you have a "masterplan"? Your "RFC's" are "offline" (i found them in the respository history). What style do you preffer, posix style? (posix is not exaclty what we need, because we are object orientated, but some standart we should take, for example the idea of the "root" file system and flexible mounting).

So, where i can discuss such things? IRC seems to be dead...

**Comment by charsleysa** [comment]
The best place to discuss things would be here on GitHub.

You can also contact myself and @tgiphil by email.

There is a lot of work to do but there is also a lot of work that has been done over the past year.
You'll see that some major improvements since this time last year is a plethora of bug fixes, Exception Handling, clear and concise Metadata, the beginnings of Reflection.

`For example, why don't you use UIntPtr instead of uint32 when working with memory pointers? It's better for future x64 support.`
The compiler uses platform-agnostic pointers wherever possible.

Also a note to mention is that we follow strict C# primitive type sizing, which means uint will always be 32bit no matter what platform, same for ulong being 64bit no matter what platform (including x86).

When creating code specific to a certain platform, using UIntPtr has a major increase in overhead since it cannot be optimized well by the C# and MOSA compilers.

I should note that while we retain the MOSA is a managed operating system, we do have many areas of unsafe code which is mostly for the low level Runtime stuff that is just impossible to write using standard C# (which is where our custom compiler comes in).

We definitely need better documentation but it's hard enough to find the time to complete these massive features let alone fully document them.

The biggest thing to note about this project is that we are doing everything in a managed way, so those existing concepts you're used to (such as POSIX) don't fit with our goals since they were designed with unmanaged code in mind.

**Comment by tgiphil** [comment]
@Arakis Hi! Welcome to the MOSA project. 

What Linux distribution did you use? And did you compile Mono from scratch?

**Comment by tgiphil** [comment]
Under **linux1** branch in my repo, PreserveSigAttribute class has been added and "warnings as errors" turned off. Now, the MOSA project compiles on Linux with Mono. But the following run-time error message is displayed when attempting to compile an assembly:
<pre>
System.InvalidOperationException: Failed to find override method slot.
  at Mosa.Compiler.Framework.MosaTypeLayout.FindOverrideSlot (IList`1 methodTable, Mosa.Compiler.MosaTypeSystem.MosaMethod method) [0x00000] in <filename unknown>:0 
  at Mosa.Compiler.Framework.MosaTypeLayout.CreateMethodTable (Mosa.Compiler.MosaTypeSystem.MosaType type) [0x00000] in <filename unknown>:0 
</pre>

Can someone cherry pick these changes and merge into **master**? **linux1** is a fork of the **vgadriver2** branch; however that branch crashes CoolWorld. Until that is fixed, we can not merge in the work from *vgadriver2* branch yet.

**Comment by charsleysa** [comment]
@tgiphil I'll be merging in the changes to my metadata branch, then once that branch is polished I'll be merging it into master.

**Comment by tgiphil** [comment]
@charsleysa Thanks!

**Comment by Arakis** [comment]
@tgiphil I'm using Arch Linux (rolling distribution). Yesterday, i compiled mono from scratch only for debugging the mono compiler. Normally, i use only the binaries.

Wich code style you are using, VSStudio default, or MonoDevelop default? Or a own rule-set? I'm a fan of auto format file on save - but for that all need the same format rule.

I'm fixing some other unix related bugs (in the launcher) in the moment.

Some other question:
- Gargabe collections is not implemented, as i read. So every new operator will create an undeletable object?
- Which protection rings are you using (for example, kernel=ring 0, user space = ring 3?
- As i read, every process will executed in its own runtime. The code of the runtime machine itself (not the IL code of the executing assembly), will it be shared over all processes? (for performance reasons).
- Will garbage collection executed system wide or only per process? I mean, will be there "one" system wide thread, that triggers the garbage collection for all user processes?
- Important tip: starting new process **should** be so fast as creating a new thread (in a final implementation). For example, on unix, creating a process is nearly as cheap as creating a new thread.

Some github related questions:
- when i make a pull request, and i want to update it (because of making more changes), how to update the pull request?
- How can i get/merge the changes from the main repo into my fork, without loosing the changes in my fork?

**Comment by charsleysa** [comment]
Currently there is no garbage collection so every new object is unable to be deleted. 

We haven't configured any protection rings so it's using the default (which I think is ring 0).

Individual processes will have their own runtime instance using a jitter, but we are very far away from that. 
Please note that this is different from the kernel runtime which we currently work with. 

Starting a new process is very different from starting a new thread in C# and that's how mosa will be doing it since its a managed operating system. I'm not sure how much detail the specifications have for threading but that's our guide when building features, though we usually change things here and there if we can do it better. 

Github pull requests are automatically updated as long as the changes are made on the same branch. 

If you will be making changes to your fork I would suggest leaving the master branch the exact same as the main repo and instead have a separate branch for your changes. 

To get updates from the main repo to your master branch I would recommend following these instructions: https://help.github.com/articles/syncing-a-fork/

**Comment by Arakis** [comment]
After getting the latest sources, i must add the Dictionary<K, T> class (compiler needed this "predefnied type). And i fixed some path problems in AppLocations.cs.

Launcher starts, after selecting a Source, and clicking on "Compie and Run", it will switch so "Output", but i will be blank. I try to debug, why nothing happens.

**Comment by Arakis** [comment]
dnlib hangs in an endless loop, since i added Dictionary/KeyValuePair:
```
dnlib.DotNet.SigComparer.Equals (a={System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<!0,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>}, b={System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<System.Collections.Generic.KeyValuePair`2<!0,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>,!1>}) in 
```
Why do you use the cecil loader from mono.cecil?
